# Generated by Django 6.0.3 on 2026-03-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
    ]
