# Generated by Django 6.0.3 on 2026-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('HOD', 'HOD'), ('DEP_EXAMS_COORD', 'Department Exams Coordinator'), ('SCH_EXAMS_COORD', 'School Exams Coordinator'), ('LECTURER', 'Lecturer'), ('DEAN', 'Dean')], default='STUDENT', max_length=35),
        ),
    ]
