# Generated by Django 6.0.3 on 2026-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_gender_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+233 547 50 6665', max_length=15),
            preserve_default=False,
        ),
    ]
