# Generated by Django 6.0.5 on 2026-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('hod', 'Head of Department'), ('dept_coordinator', 'Departmental Exams Coordinator'), ('university_coordinator', 'University Exams Coordinator')], default='student', max_length=40),
        ),
    ]
