# Generated by Django 6.0.5 on 2026-06-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('hod', 'Head of Department'), ('dept_coordinator', 'Departmental Exams Coordinator'), ('university_coordinator', 'University Exams Coordinator'), ('administrator', 'Administrator')], default='student', max_length=40),
        ),
    ]
