# Generated by Django 6.0.5 on 2026-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='min_graduation_credits',
            field=models.PositiveIntegerField(default=120, help_text='Minimum credits required to be eligible for graduation'),
        ),
    ]
