# Generated by Django 6.0.5 on 2026-05-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourse',
            name='is_core',
            field=models.BooleanField(default=True),
        ),
    ]
