# Generated by Django 6.0.3 on 2026-03-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0003_student_programme_dean_hod_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hod'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='school',
            name='dean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dean'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.school'),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'lecturer', 'academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'code', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('name', 'department')},
        ),
    ]
