# Generated by Django 6.0.3 on 2026-03-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd')])),
                ('level', models.PositiveIntegerField()),
                ('min_credits', models.PositiveIntegerField(default=15)),
                ('max_credits', models.PositiveIntegerField(default=21)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd')])),
                ('level', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.programme')),
            ],
        ),
    ]
