# Generated by Django 6.0.3 on 2026-03-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_programmerequirement_alter_course_unique_together_and_more'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmecourse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.academicsession'),
        ),
        migrations.AddField(
            model_name='programmerequirement',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.programme'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
        migrations.AlterUniqueTogether(
            name='programmecourse',
            unique_together={('programme', 'course', 'session', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='programmerequirement',
            unique_together={('programme', 'semester', 'level')},
        ),
    ]
