# Generated by Django 6.0.3 on 2026-03-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_programmerequirement_alter_course_unique_together_and_more'),
        ('accounts', '0004_alter_student_session_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd')])),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='academics.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.programme')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')])),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='registry.academicsession')),
            ],
            options={
                'unique_together': {('session', 'number')},
            },
        ),
    ]
