# Generated by Django 6.0.3 on 2026-03-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Fully Registered'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15),
        ),
    ]
