"""
Export service — generates PDF and Excel from report dicts.
"""
import io
from datetime import datetime

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (SimpleDocTemplate, Table, TableStyle,
                                  Paragraph, Spacer, HRFlowable)

NAVY  = colors.HexColor('#0f2744')
BLUE  = colors.HexColor('#2563eb')
GOLD  = colors.HexColor('#f59e0b')
RED   = colors.HexColor('#dc2626')
GREEN = colors.HexColor('#16a34a')
GRAY  = colors.HexColor('#f1f5f9')


def _pdf_header(story, title, subtitle, generated_by):
    styles = getSampleStyleSheet()
    story.append(Paragraph(
        'UNIVERSITY OF ENERGY AND NATURAL RESOURCES',
        ParagraphStyle('H', fontSize=15, alignment=TA_CENTER, textColor=NAVY, fontName='Helvetica-Bold', spaceAfter=2)
    ))
    story.append(Paragraph(
        'UENR STARS — Academic Management System',
        ParagraphStyle('S', fontSize=10, alignment=TA_CENTER, textColor=BLUE, spaceAfter=2)
    ))
    story.append(Paragraph(title, ParagraphStyle('T', fontSize=13, alignment=TA_CENTER, textColor=NAVY, fontName='Helvetica-Bold', spaceAfter=2)))
    if subtitle:
        story.append(Paragraph(subtitle, ParagraphStyle('Sub', fontSize=10, alignment=TA_CENTER, spaceAfter=4)))
    story.append(HRFlowable(width='100%', thickness=2, color=NAVY))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f'Generated: {datetime.now().strftime("%d %b %Y %H:%M")}   |   Generated by: {generated_by}',
        ParagraphStyle('Meta', fontSize=8, textColor=colors.gray, alignment=TA_CENTER, spaceAfter=8)
    ))


def _table_style(header_row=True):
    style = [
        ('FONTSIZE',   (0,0), (-1,-1), 9),
        ('PADDING',    (0,0), (-1,-1), 4),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, GRAY]),
        ('GRID',       (0,0), (-1,-1), 0.4, colors.HexColor('#aaccee')),
        ('ALIGN',      (0,0), (-1,-1), 'CENTER'),
    ]
    if header_row:
        style += [
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('TEXTCOLOR',  (0,0), (-1,0), colors.white),
            ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ]
    return TableStyle(style)


# ── Course Offering PDF ──────────────────────────────────────────────────────

def course_pdf(report_data, generated_by='System'):
    buffer = io.BytesIO()
    course = report_data.get('course', {})
    analytics = report_data.get('analytics', {})
    rows = report_data.get('rows', [])

    doc = SimpleDocTemplate(buffer, pagesize=landscape(A4),
                             topMargin=1.5*cm, bottomMargin=1.5*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    story = []
    _pdf_header(story, 'Course Offering Report',
                f"{course.get('code','')} — {course.get('title','')} | Dept: {course.get('department','')}",
                generated_by)

    # Summary row
    summary_data = [
        ['Total Students', 'Pass', 'Fail', 'Pass %', 'Avg Score', 'High', 'Low'],
        [
            str(analytics.get('total_students',0)),
            str(analytics.get('pass_count',0)),
            str(analytics.get('fail_count',0)),
            f"{analytics.get('pass_rate',0)}%",
            str(analytics.get('avg_score',0)),
            str(analytics.get('highest_score',0)),
            str(analytics.get('lowest_score',0)),
        ]
    ]
    summary_table = Table(summary_data, colWidths=[3.5*cm]*7)
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), BLUE),
        ('TEXTCOLOR',  (0,0), (-1,0), colors.white),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 9),
        ('ALIGN',      (0,0), (-1,-1), 'CENTER'),
        ('GRID',       (0,0), (-1,-1), 0.5, colors.HexColor('#aaccee')),
        ('BACKGROUND', (0,1), (-1,-1), GRAY),
        ('FONTNAME',   (0,1), (-1,1), 'Helvetica-Bold'),
        ('PADDING',    (0,0), (-1,-1), 5),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.4*cm))

    # Main table
    headers = ['#', 'Index No.', 'Student Name', 'Department', 'Programme', 'Year', 'CA', 'Exam', 'Total', 'Grade', 'Status']
    col_w = [0.8*cm, 3*cm, 5*cm, 4*cm, 4*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 2*cm]
    data = [headers]
    for i, r in enumerate(rows, 1):
        data.append([
            str(i), r['index_number'], r['full_name'],
            r['department'][:18], r['programme'][:18],
            str(r['year_of_study']),
            str(r['ca'] or '-'), str(r['exam'] or '-'), str(r['total'] or '-'),
            r['grade'], 'Pass' if r['pass'] else 'Fail',
        ])
    t = Table(data, colWidths=col_w, repeatRows=1)
    t.setStyle(_table_style())
    # Colour fail rows red
    for i, r in enumerate(rows, 1):
        if not r['pass']:
            t.setStyle(TableStyle([('BACKGROUND', (0,i), (-1,i), colors.HexColor('#fff5f5'))]))
    story.append(t)

    # Signatures
    story.append(Spacer(1, 0.8*cm))
    story.append(HRFlowable(width='100%', thickness=1, color=NAVY))
    sig_data = [['Prepared by: ___________________', 'HOD Signature: ___________________', 'Date: ___________________']]
    sig_t = Table(sig_data, colWidths=[8*cm, 8*cm, 7*cm])
    sig_t.setStyle(TableStyle([('FONTSIZE',(0,0),(-1,-1),9), ('ALIGN',(0,0),(-1,-1),'CENTER')]))
    story.append(Spacer(1, 0.3*cm))
    story.append(sig_t)

    doc.build(story)
    buffer.seek(0)
    return buffer


# ── Department Report PDF ─────────────────────────────────────────────────────

def department_pdf(report_data, generated_by='System'):
    buffer = io.BytesIO()
    dept = report_data.get('department', {})
    summary = report_data.get('summary', {})
    rows = report_data.get('rows', [])

    doc = SimpleDocTemplate(buffer, pagesize=landscape(A4),
                             topMargin=1.5*cm, bottomMargin=1.5*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    story = []
    _pdf_header(story, 'Department Academic Results Report',
                f"Department: {dept.get('name','')} ({dept.get('code','')})",
                generated_by)

    # Summary
    sum_data = [
        ['Total','Avg GPA','First Class','2nd Upper','2nd Lower','Third','Fail','In Danger'],
        [str(summary.get('total',0)), str(summary.get('avg_gpa',0)),
         str(summary.get('first_class',0)), str(summary.get('second_upper',0)),
         str(summary.get('second_lower',0)), str(summary.get('third_class',0)),
         str(summary.get('fail',0)), str(summary.get('in_danger',0))]
    ]
    st = Table(sum_data, colWidths=[3*cm]*8)
    st.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),NAVY), ('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'), ('FONTSIZE',(0,0),(-1,-1),9),
        ('ALIGN',(0,0),(-1,-1),'CENTER'), ('GRID',(0,0),(-1,-1),0.4,colors.HexColor('#aaccee')),
        ('BACKGROUND',(0,1),(-1,-1),GRAY), ('PADDING',(0,0),(-1,-1),5),
    ]))
    story.append(st)
    story.append(Spacer(1, 0.4*cm))

    headers = ['#','Index No.','Name','Programme','Yr','Status','CuGPA','Standing','Trails','Danger']
    col_w = [0.8*cm,3*cm,5*cm,5*cm,1.2*cm,2.2*cm,1.8*cm,4*cm,1.5*cm,2*cm]
    data = [headers]
    for i, r in enumerate(rows, 1):
        data.append([
            str(i), r['index_number'], r['full_name'],
            r['programme'][:20], str(r['current_year']), r['status'].title(),
            str(r['cumulative_gpa']), r['academic_standing'],
            str(r['trail_count']), '⚠ YES' if r['in_danger'] else 'No',
        ])
    t = Table(data, colWidths=col_w, repeatRows=1)
    t.setStyle(_table_style())
    for i, r in enumerate(rows, 1):
        if r['in_danger']:
            t.setStyle(TableStyle([('BACKGROUND',(0,i),(-1,i),colors.HexColor('#fff5f5'))]))
    story.append(t)

    story.append(Spacer(1, 0.8*cm))
    story.append(HRFlowable(width='100%', thickness=1, color=NAVY))
    sig_data = [['Exams Coordinator: ___________________', 'HOD: ___________________', 'Date: ___________________']]
    sig_t = Table(sig_data, colWidths=[9*cm, 8*cm, 7*cm])
    sig_t.setStyle(TableStyle([('FONTSIZE',(0,0),(-1,-1),9), ('ALIGN',(0,0),(-1,-1),'CENTER')]))
    story.append(Spacer(1, 0.3*cm))
    story.append(sig_t)

    doc.build(story)
    buffer.seek(0)
    return buffer


# ── Excel export (generic) ────────────────────────────────────────────────────

def to_excel(headers, rows_data, sheet_title='Report', summary_data=None):
    """
    headers   : list of column names
    rows_data : list of dicts (keys matching headers, lowercased/underscored)
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_title

    HEADER_FILL = PatternFill('solid', fgColor='0F2744')
    HEADER_FONT = Font(color='FFFFFF', bold=True, size=10)
    ALT_FILL    = PatternFill('solid', fgColor='F1F5F9')
    BOLD        = Font(bold=True)
    BORDER      = Border(
        left=Side(style='thin', color='AACCEE'),
        right=Side(style='thin', color='AACCEE'),
        top=Side(style='thin', color='AACCEE'),
        bottom=Side(style='thin', color='AACCEE'),
    )

    # Title
    ws.merge_cells('A1:' + get_column_letter(len(headers)) + '1')
    ws['A1'] = 'UENR STARS — ' + sheet_title
    ws['A1'].font = Font(bold=True, size=13, color='0F2744')
    ws['A1'].alignment = Alignment(horizontal='center')

    ws.merge_cells('A2:' + get_column_letter(len(headers)) + '2')
    ws['A2'] = f'Generated: {datetime.now().strftime("%d %b %Y %H:%M")}'
    ws['A2'].font = Font(size=9, color='64748b', italic=True)
    ws['A2'].alignment = Alignment(horizontal='center')

    # Headers at row 4
    for ci, h in enumerate(headers, 1):
        cell = ws.cell(row=4, column=ci, value=h)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal='center')
        cell.border = BORDER

    # Data rows
    header_keys = [h.lower().replace(' ', '_').replace('.', '') for h in headers]
    for ri, row in enumerate(rows_data, 5):
        for ci, key in enumerate(header_keys, 1):
            # Try exact key then positional
            val = row.get(key, row.get(headers[ci-1].lower().replace(' ','_'), ''))
            cell = ws.cell(row=ri, column=ci, value=val)
            cell.border = BORDER
            cell.alignment = Alignment(horizontal='center')
            if ri % 2 == 0:
                cell.fill = ALT_FILL

    # Summary sheet if provided
    if summary_data:
        ws2 = wb.create_sheet('Summary')
        ws2['A1'] = 'Summary Statistics'
        ws2['A1'].font = Font(bold=True, size=12, color='0F2744')
        for i, (k, v) in enumerate(summary_data.items(), 2):
            ws2.cell(row=i, column=1, value=k).font = BOLD
            ws2.cell(row=i, column=2, value=str(v))

    # Auto-width
    for col in ws.columns:
        max_len = max((len(str(cell.value or '')) for cell in col), default=10)
        ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 4, 40)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
