# Generated by Django 6.0.3 on 2026-03-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=10, unique=True)),
                ('session', models.CharField(choices=[('FULL_TIME', 'Full time'), ('WEEKEND', 'Weekend')], max_length=10)),
                ('fee_payment', models.CharField(choices=[('REGULAR', 'Regular'), ('FEE_PAYING', 'Fee Paying')], max_length=10)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('REPEATED', 'Repeated'), ('DEFERRED', 'Deferred')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
