# Generated by Django 6.0.3 on 2026-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
