# Generated by Django 6.0.5 on 2026-05-25 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='priority_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='priority_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievance',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='grievance_type',
            field=models.CharField(choices=[('result', 'Result Issue'), ('registration', 'Registration Issue'), ('grade', 'Grade Dispute'), ('timetable', 'Timetable Conflict'), ('portal', 'Portal / System Issue'), ('lecturer', 'Lecturer Complaint'), ('graduation', 'Graduation Issue'), ('transcript', 'Transcript Issue'), ('feedback', 'General Feedback'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='System-assigned; staff may override', max_length=10),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'Under Review'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='GrievancePriorityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_priority', models.CharField(max_length=10)),
                ('new_priority', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_logs', to='grievances.grievance')),
            ],
        ),
    ]
