# Generated by Django 6.0.5 on 2026-06-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_grievance_priority_override_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
